version: "3.8"
services:
  frontend:
    build:
      context: ./Interface
      dockerfile: Dockerfile
    container_name: frontend

  backend:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    container_name: backend

